bu: bu1
projects:
  project1:
    description: project1 description
    team_project_access:
      team1:
        access: "maintain"
        sso_team_id: null
  project2:
    description: project2 description
    team_project_access:
      team2:
        access: "maintain"
        sso_team_id: null
