bu: bu1
projects:
  data_plaform1:
    description: data_plaform datazone domain
    team_project_access:
      data_plaform1_maintain:
        team:
          access: "maintain"
  data_project1:
    description: data_environment 1
    team_project_access:
      data_project1_maintain:
        team:
          access: "maintain"
  data_project2:
    description: data_environment 1
    team_project_access:
      data_project2_maintain:
        team:
          access: "maintain"
