bu: bu2
projects:
  project1:
    description: project1 description
    team_project_access:
      team3:
        access: "maintain"
        sso_team_id: null
  project2:
    description: project2 description
    team_project_access:
      team4:
        access: "maintain"
        sso_team_id: null