bu: bu2
projects:
  data_platform2:
    name: data_platform2
    description: data_platform 2 description
    team_project_access:
      data_platform2_maintain:
        team:
          access: "maintain"
          sso_team_id: null
      data_platform2_write:
        team:
          access: "write"