bu: bu2
projects:
  data_plaform1:
    description: project1 description
    team_project_access:
      project1_maintain:
        team:
          access: "maintain"
          sso_team_id: null
  data_project1:
    description: project2 description
    team_project_access:
      project2_maintain:
        team:
          access: "maintain"
          sso_team_id: null