bu: bu1
projects:
  data_plaform1:
    name: data_platform1
    description: data_plaform datazone domain
    team_project_access:
      data_platform1_maintain:
        team:
          access: "maintain"
      data_platform1_write:
        team:
          access: "write"
  data_plaform2:
    name: data_platform2
    description: data_platform datazone domain
    team_project_access:
      data_platform2_maintain:
        team:
          access: "maintain"
      data_platform2_write:
        team:
          access: "write"