workspace_name: bu1_data_plaform1_ws
project_name: bu1_data_plaform1
create_repo: true
create_variable_set: false
github:
  github_repo_name: "bu1_data_plaform1_ws"
  github_repo_desc: "created by terraform"
  github_repo_visibility: "public"
  github_template_owner: "hashi-demo-lab"
  github_template_repo: "template-datazone-domain"
vcs_repo:
  identifier: hashi-demo-lab/bu1_data_plaform1_ws
  branch: main
variables:
      datazone_domain_name:
        category: terraform
        description:
        hcl: false
        sensitive: false
        value: bu1_data_plaform1