workspace_name: redshift_cluster1
project_name: bu1_data_project1
create_repo: true
create_variable_set: false
github:
  github_repo_name: "redshift_cluster1"
  github_repo_desc: "created by terraform"
  github_repo_visibility: "public"
  github_template_owner: "hashi-demo-lab"
  github_template_repo: "template-redshift-cluster"
vcs_repo:
  identifier: hashi-demo-lab/redshift_cluster1
  branch: main


