workspace_name: vcs-driven-newrepo
project_name: bu1_project1
create_repo: true
create_variable_set: false
github:
  github_repo_name: "createrepotest3"
  github_repo_desc: "Rep created by terraform"
  github_repo_visibility: "public"
  github_template_owner: "hashi-demo-lab"
  github_template_repo: "tf-template"
vcs_repo:
  identifier: hashi-demo-lab/createrepotest3
  branch: main