bu: retail
projects:
  data_prod:
    name: data_prod
    description: cdao prod data platform
    team_project_access:
      data_prod_maintain:
        team:
          access: "maintain"
      data_prod_write:
        team:
          access: "write"
  data_nonprod:
    name: data_nonprod
    description: cdao prod data platform
    team_project_access:
      data_nonprod_maintain:
        team:
          access: "maintain"
      data_nonprod_write:
        team:
          access: "write"
     